name: ItemFrameShop
author: PerezHD, Kassestral
version: 1.0.9
main: me.perezhd.kassestral.bishop.Plugin
description: A item frame shop plugin!
depend: [Vault]
commands:
  ifs:
    description: The main command!